# Generated by Django 5.0.3 on 2024-04-15 17:32

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='', verbose_name=django.contrib.auth.models.User),
        ),
    ]
